### PR TITLE
prepare for final v1 release

### PR DESCRIPTION
**Pull request by h-bragg**
Checklist to ensure everything is ready for v1

- [ ] Sensible documentation
- [ ] Consistency in the code (does anything jump out that doesn't really make sense)
- [ ] Code readability
- [ ] Test coverage
- [ ] Test quality (Are they rubbish, or easily readable?)

### CODE REVIEW

**Comment by biggianteye** [comment]
This looks to be just final documentation changes. Is there anything specific you would like me to look at and/or qa, given that I have never looked at this library before?

**Comment by h-bragg** [comment]
Sorry; should have added some bits to check for; does the PR description make sense?

**Comment by biggianteye** [comment]
I've had a quick look around and here are my thoughts so far. I'll look at it some more later:

- Consider having `make help` be the default build target.
- Not all of the `performance` tests have assertions so it's unclear what they are testing and what the failure condition should be.
- 👍  for test matrix
- `make clean` tries to remove `latest` but the tag in use is `test`.
- 👍  for 100% in the code coverage tests
- HHVM tests fail. Given you've indicated that this is fine in the travis file, I'm guessing you know about this?
- If the HHVM tests pass, consider having the test matrix be part of `make test` given this is open source and we don't know what php version people will be using.
- `make lint-fix` fails:
```
patch: can't open 'PHP_CodeSniffer': No such file or directory
Array
(
    [0] => patching file PHP_CodeSniffer
)
Returned: 1
```

**Comment by h-bragg** [comment]
- hhvm tests fail because they have a bug with date times where they don't support timezones ❗️ 
- `make lint-fix` works for me... will catch up tomorrow
- removed `make clean` as it is irrelevant now
- made help the default target
- added checks for each performance test
- added php7.1 in test matrix

**Pull request merged**
